/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import br.com.safeguard.check.SafeguardCheck;
import br.com.safeguard.types.ParametroTipo;
import org.junit.Test;
import static org.junit.Assert.*;


public class CreditAnalyzerTest {

    @Test public void testAllowedUserHasCreditAvailable() {
        CreditAnalyzer creditAnalyzer = new CreditAnalyzerImpl();
        String userDocument = "00000000191";
        Integer userScore = 600;

        boolean creditAvailable = creditAnalyzer.validateCreditAvailable(userDocument, userScore);
        assertTrue("User should have credit available", creditAvailable);
    }

    @Test public void testAllowedUserHasNotCreditAvailable() {
        CreditAnalyzer creditAnalyzer = new CreditAnalyzerImpl();
        String userDocument = "00000000191";
        Integer userScore = 599;

        boolean creditAvailable = creditAnalyzer.validateCreditAvailable(userDocument, userScore);
        assertFalse("User should not have credit available", creditAvailable);
    }
}
